<center> <img src = https://raw.githubusercontent.com/AndreyRysistov/DatasetsForPandas/main/hh%20label.jpg alt="drawing" style="width:400px;">

# <center> Проект: Анализ резюме из HeadHunter

In [175]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import re

# Исследование структуры данных

1. Прочитайте данные с помощью библиотеки Pandas. Совет: перед чтением обратите внимание на разделитель внутри файла.

In [178]:
hhdata=pd.read_csv("hhdata.csv", sep=";")
hhdata.head()

,"Пол, возраст",ЗП,Ищет работу на должность:,"Город, переезд, командировки",Занятость,График,Опыт работы,Последнее/нынешнее место работы,Последняя/нынешняя должность,Образование и ВУЗ,Обновление резюме,Авто
0,"Мужчина , 39 лет , родился 27 ноября 1979",29000 руб.,Системный администратор,"Советск (Калининградская область) , не готов к...","частичная занятость, проектная работа, полная ...","гибкий график, полный день, сменный график, ва...",Опыт работы 16 лет 10 месяцев Август 2010 — п...,"МАОУ ""СОШ № 1 г.Немана""",Системный администратор,Неоконченное высшее образование 2000 Балтийск...,16.04.2019 15:59,Имеется собственный автомобиль
1,"Мужчина , 60 лет , родился 20 марта 1959",40000 руб.,Технический писатель,"Королев , не готов к переезду , готов к редким...","частичная занятость, проектная работа, полная ...","гибкий график, полный день, сменный график, уд...",Опыт работы 19 лет 5 месяцев Январь 2000 — по...,Временный трудовой коллектив,"Менеджер проекта, Аналитик, Технический писатель",Высшее образование 1981 Военно-космическая ак...,12.04.2019 08:42,Не указано
2,"Женщина , 36 лет , родилась 12 августа 1982",20000 руб.,Оператор,"Тверь , не готова к переезду , не готова к ком...",полная занятость,полный день,Опыт работы 10 лет 3 месяца Октябрь 2004 — Де...,ПАО Сбербанк,Кассир-операционист,Среднее специальное образование 2002 Профессио...,16.04.2019 08:35,Не указано
3,"Мужчина , 38 лет , родился 25 июня 1980",100000 руб.,Веб-разработчик (HTML / CSS / JS / PHP / базы ...,"Саратов , не готов к переезду , готов к редким...","частичная занятость, проектная работа, полная ...","гибкий график, удаленная работа",Опыт работы 18 лет 9 месяцев Август 2017 — Ап...,OpenSoft,Инженер-программист,Высшее образование 2002 Саратовский государст...,08.04.2019 14:23,Не указано
4,"Женщина , 26 лет , родилась 3 марта 1993",140000 руб.,Региональный менеджер по продажам,"Москва , не готова к переезду , готова к коман...",полная занятость,полный день,Опыт работы 5 лет 7 месяцев Региональный мене...,Мармелад,Менеджер по продажам,Высшее образование 2015 Кгу Психологии и педаг...,22.04.2019 10:32,Не указано

In [176]:
hhdata=pd.read_csv("s3://1stDLBucket/hhdata01.csv", sep=";", storage_options={
"key": '00369a8ecf2122c0000000001',
"secret": 'K003l9Z8bH6j0pGzDXVDylPUNh7S040',
"endpoint_url": "https://s3.eu-central-003.backblazeb2.com"
}
)
hhdata.head(5)

OSError: [Errno 5] An error occurred (401) when calling the HeadObject operation: Unauthorized

2. Выведите несколько первых (последних) строк таблицы, чтобы убедиться в том, что ваши данные не повреждены. Ознакомьтесь с признаками и их структурой.

In [ ]:
hhdata.head()

,"Пол, возраст",ЗП,Ищет работу на должность:,"Город, переезд, командировки",Занятость,График,Опыт работы,Последнее/нынешнее место работы,Последняя/нынешняя должность,Образование и ВУЗ,Обновление резюме,Авто
0,"Мужчина , 39 лет , родился 27 ноября 1979",29000 руб.,Системный администратор,"Советск (Калининградская область) , не готов к...","частичная занятость, проектная работа, полная ...","гибкий график, полный день, сменный график, ва...",Опыт работы 16 лет 10 месяцев Август 2010 — п...,"МАОУ ""СОШ № 1 г.Немана""",Системный администратор,Неоконченное высшее образование 2000 Балтийск...,16.04.2019 15:59,Имеется собственный автомобиль
1,"Мужчина , 60 лет , родился 20 марта 1959",40000 руб.,Технический писатель,"Королев , не готов к переезду , готов к редким...","частичная занятость, проектная работа, полная ...","гибкий график, полный день, сменный график, уд...",Опыт работы 19 лет 5 месяцев Январь 2000 — по...,Временный трудовой коллектив,"Менеджер проекта, Аналитик, Технический писатель",Высшее образование 1981 Военно-космическая ак...,12.04.2019 08:42,Не указано
2,"Женщина , 36 лет , родилась 12 августа 1982",20000 руб.,Оператор,"Тверь , не готова к переезду , не готова к ком...",полная занятость,полный день,Опыт работы 10 лет 3 месяца Октябрь 2004 — Де...,ПАО Сбербанк,Кассир-операционист,Среднее специальное образование 2002 Профессио...,16.04.2019 08:35,Не указано
3,"Мужчина , 38 лет , родился 25 июня 1980",100000 руб.,Веб-разработчик (HTML / CSS / JS / PHP / базы ...,"Саратов , не готов к переезду , готов к редким...","частичная занятость, проектная работа, полная ...","гибкий график, удаленная работа",Опыт работы 18 лет 9 месяцев Август 2017 — Ап...,OpenSoft,Инженер-программист,Высшее образование 2002 Саратовский государст...,08.04.2019 14:23,Не указано
4,"Женщина , 26 лет , родилась 3 марта 1993",140000 руб.,Региональный менеджер по продажам,"Москва , не готова к переезду , готова к коман...",полная занятость,полный день,Опыт работы 5 лет 7 месяцев Региональный мене...,Мармелад,Менеджер по продажам,Высшее образование 2015 Кгу Психологии и педаг...,22.04.2019 10:32,Не указано

3. Выведите основную информацию о числе непустых значений в столбцах и их типах в таблице.

4. Обратите внимание на информацию о числе непустых значений.

In [ ]:
hhdata.info()

<class 'pandas.DataFrame'>
RangeIndex: 44744 entries, 0 to 44743
Data columns (total 12 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Пол, возраст                     44744 non-null  str
 1   ЗП                               44744 non-null  str
 2   Ищет работу на должность:        44744 non-null  str
 3   Город, переезд, командировки     44744 non-null  str
 4   Занятость                        44744 non-null  str
 5   График                           44744 non-null  str
 6   Опыт работы                      44576 non-null  str
 7   Последнее/нынешнее место работы  44743 non-null  str
 8   Последняя/нынешняя должность     44742 non-null  str
 9   Образование и ВУЗ                44744 non-null  str
 10  Обновление резюме                44744 non-null  str
 11  Авто                             44744 non-null  str
dtypes: str(12)
memory usage: 4.1 MB

5. Выведите основную статистическую информацию о столбцах.

In [ ]:
hhdata.describe()

,"Пол, возраст",ЗП,Ищет работу на должность:,"Город, переезд, командировки",Занятость,График,Опыт работы,Последнее/нынешнее место работы,Последняя/нынешняя должность,Образование и ВУЗ,Обновление резюме,Авто
count,44744,44744,44744,44744,44744,44744,44576,44743,44742,44744,44744,44744
unique,16003,690,14929,10063,38,47,44413,30214,16927,40148,18838,2
top,"Мужчина , 32 года , родился 17 сентября 1986",50000 руб.,Системный администратор,"Москва , не готов к переезду , не готов к кома...",полная занятость,полный день,Опыт работы 10 лет 8 месяцев Апрель 2018 — по...,Индивидуальное предпринимательство / частная п...,Системный администратор,Высшее образование 2014 Московский технически...,07.05.2019 09:50,Не указано
freq,18,4064,3099,1261,30026,22727,3,935,2062,4,25,32268

# Преобразование данных

1. Начнем с простого - с признака **"Образование и ВУЗ"**. Его текущий формат это: **<Уровень образования год выпуска ВУЗ специальность...>**. Например:
* Высшее образование 2016 Московский авиационный институт (национальный исследовательский университет)...
* Неоконченное высшее образование 2000  Балтийская государственная академия рыбопромыслового флота…
Нас будет интересовать только уровень образования.

Создайте с помощью функции-преобразования новый признак **"Образование"**, который должен иметь 4 категории: "высшее", "неоконченное высшее", "среднее специальное" и "среднее".

Выполните преобразование, ответьте на контрольные вопросы и удалите признак "Образование и ВУЗ".

Совет: обратите внимание на структуру текста в столбце **"Образование и ВУЗ"**. Гарантируется, что текущий уровень образования соискателя всегда находится в первых 2ух слов и начинается с заглавной буквы. Воспользуйтесь этим.

*Совет: проверяйте полученные категории, например, с помощью метода unique()*

In [ ]:
hhdata['Образование'] = hhdata['Образование и ВУЗ'].apply(lambda x: x.split(' обр')[:1])
#hhdata.drop('Образование', axis=1, inplace=False)

hhdata.head()

,"Пол, возраст",ЗП,Ищет работу на должность:,"Город, переезд, командировки",Занятость,График,Опыт работы,Последнее/нынешнее место работы,Последняя/нынешняя должность,Образование и ВУЗ,Обновление резюме,Авто,Образование
0,"Мужчина , 39 лет , родился 27 ноября 1979",29000 руб.,Системный администратор,"Советск (Калининградская область) , не готов к...","частичная занятость, проектная работа, полная ...","гибкий график, полный день, сменный график, ва...",Опыт работы 16 лет 10 месяцев Август 2010 — п...,"МАОУ ""СОШ № 1 г.Немана""",Системный администратор,Неоконченное высшее образование 2000 Балтийск...,16.04.2019 15:59,Имеется собственный автомобиль,[Неоконченное высшее]
1,"Мужчина , 60 лет , родился 20 марта 1959",40000 руб.,Технический писатель,"Королев , не готов к переезду , готов к редким...","частичная занятость, проектная работа, полная ...","гибкий график, полный день, сменный график, уд...",Опыт работы 19 лет 5 месяцев Январь 2000 — по...,Временный трудовой коллектив,"Менеджер проекта, Аналитик, Технический писатель",Высшее образование 1981 Военно-космическая ак...,12.04.2019 08:42,Не указано,[Высшее]
2,"Женщина , 36 лет , родилась 12 августа 1982",20000 руб.,Оператор,"Тверь , не готова к переезду , не готова к ком...",полная занятость,полный день,Опыт работы 10 лет 3 месяца Октябрь 2004 — Де...,ПАО Сбербанк,Кассир-операционист,Среднее специальное образование 2002 Профессио...,16.04.2019 08:35,Не указано,[Среднее специальное]
3,"Мужчина , 38 лет , родился 25 июня 1980",100000 руб.,Веб-разработчик (HTML / CSS / JS / PHP / базы ...,"Саратов , не готов к переезду , готов к редким...","частичная занятость, проектная работа, полная ...","гибкий график, удаленная работа",Опыт работы 18 лет 9 месяцев Август 2017 — Ап...,OpenSoft,Инженер-программист,Высшее образование 2002 Саратовский государст...,08.04.2019 14:23,Не указано,[Высшее]
4,"Женщина , 26 лет , родилась 3 марта 1993",140000 руб.,Региональный менеджер по продажам,"Москва , не готова к переезду , готова к коман...",полная занятость,полный день,Опыт работы 5 лет 7 месяцев Региональный мене...,Мармелад,Менеджер по продажам,Высшее образование 2015 Кгу Психологии и педаг...,22.04.2019 10:32,Не указано,[Высшее]

In [ ]:
hhdata['Образование'].value_counts()

Образование
[Высшее]                 33863
[Среднее специальное]     5765
[Неоконченное высшее]     4557
[Среднее]                  559
Name: count, dtype: int64

2. Теперь нас интересует столбец **"Пол, возраст"**. Сейчас он представлен в формате **<Пол , возраст , дата рождения >**. Например:
* Мужчина , 39 лет , родился 27 ноября 1979 
* Женщина , 21 год , родилась 13 января 2000
Как вы понимаете, нам необходимо выделить каждый параметр в отдельный столбец.

Создайте два новых признака **"Пол"** и **"Возраст"**. При этом важно учесть:
* Признак пола должен иметь 2 уникальных строковых значения: 'М' - мужчина, 'Ж' - женщина. 
* Признак возраста должен быть представлен целыми числами.

Выполните преобразование, ответьте на контрольные вопросы и удалите признак **"Пол, возраст"** из таблицы.

*Совет: обратите внимание на структуру текста в столбце, в части на то, как разделены параметры пола, возраста и даты рождения между собой - символом ' , '. 
Гарантируется, что структура одинакова для всех строк в таблице. Вы можете воспользоваться этим.*

In [ ]:
hhdata['Пол'] = hhdata['Пол, возраст'].apply(lambda x: x.split(', ')[:1])
hhdata['Возраст и ДР'] = hhdata['Пол, возраст'].apply(lambda x: x.split(', ')[1:])
hhdata['Возраст'] = hhdata['Пол, возраст'].apply(lambda x: x.split(' ')[3:4]).str.get(0)
#hhdata['Возраст'] = hhdata['Возраст'].str.get(0)
hhdata['Возраст'] = hhdata['Возраст'].astype(int)


av_age = hhdata['Возраст'].mean()
print(av_age)
hhdata.head()

32.19674146254246

,"Пол, возраст",ЗП,Ищет работу на должность:,"Город, переезд, командировки",Занятость,График,Опыт работы,Последнее/нынешнее место работы,Последняя/нынешняя должность,Образование и ВУЗ,Обновление резюме,Авто,Образование,Пол,Возраст и ДР,Возраст
0,"Мужчина , 39 лет , родился 27 ноября 1979",29000 руб.,Системный администратор,"Советск (Калининградская область) , не готов к...","частичная занятость, проектная работа, полная ...","гибкий график, полный день, сменный график, ва...",Опыт работы 16 лет 10 месяцев Август 2010 — п...,"МАОУ ""СОШ № 1 г.Немана""",Системный администратор,Неоконченное высшее образование 2000 Балтийск...,16.04.2019 15:59,Имеется собственный автомобиль,[Неоконченное высшее],[Мужчина ],"[ 39 лет , родился 27 ноября 1979]",39
1,"Мужчина , 60 лет , родился 20 марта 1959",40000 руб.,Технический писатель,"Королев , не готов к переезду , готов к редким...","частичная занятость, проектная работа, полная ...","гибкий график, полный день, сменный график, уд...",Опыт работы 19 лет 5 месяцев Январь 2000 — по...,Временный трудовой коллектив,"Менеджер проекта, Аналитик, Технический писатель",Высшее образование 1981 Военно-космическая ак...,12.04.2019 08:42,Не указано,[Высшее],[Мужчина ],"[ 60 лет , родился 20 марта 1959]",60
2,"Женщина , 36 лет , родилась 12 августа 1982",20000 руб.,Оператор,"Тверь , не готова к переезду , не готова к ком...",полная занятость,полный день,Опыт работы 10 лет 3 месяца Октябрь 2004 — Де...,ПАО Сбербанк,Кассир-операционист,Среднее специальное образование 2002 Профессио...,16.04.2019 08:35,Не указано,[Среднее специальное],[Женщина ],"[ 36 лет , родилась 12 августа 1982]",36
3,"Мужчина , 38 лет , родился 25 июня 1980",100000 руб.,Веб-разработчик (HTML / CSS / JS / PHP / базы ...,"Саратов , не готов к переезду , готов к редким...","частичная занятость, проектная работа, полная ...","гибкий график, удаленная работа",Опыт работы 18 лет 9 месяцев Август 2017 — Ап...,OpenSoft,Инженер-программист,Высшее образование 2002 Саратовский государст...,08.04.2019 14:23,Не указано,[Высшее],[Мужчина ],"[ 38 лет , родился 25 июня 1980]",38
4,"Женщина , 26 лет , родилась 3 марта 1993",140000 руб.,Региональный менеджер по продажам,"Москва , не готова к переезду , готова к коман...",полная занятость,полный день,Опыт работы 5 лет 7 месяцев Региональный мене...,Мармелад,Менеджер по продажам,Высшее образование 2015 Кгу Психологии и педаг...,22.04.2019 10:32,Не указано,[Высшее],[Женщина ],"[ 26 лет , родилась 3 марта 1993]",26

3. Следующим этапом преобразуем признак **"Опыт работы"**. Его текущий формат - это: **<Опыт работы: n лет m месяцев, периоды работы в различных компаниях…>**. 

Из столбца нам необходимо выделить общий опыт работы соискателя в месяцах, новый признак назовем "Опыт работы (месяц)"

Для начала обсудим условия решения задачи:
* Во-первых, в данном признаке есть пропуски. Условимся, что если мы встречаем пропуск, оставляем его как есть (функция-преобразование возвращает NaN)
* Во-вторых, в данном признаке есть скрытые пропуски. Для некоторых соискателей в столбце стоит значения "Не указано". Их тоже обозначим как NaN (функция-преобразование возвращает NaN)
* В-третьих, нас не интересует информация, которая описывается после указания опыта работы (периоды работы в различных компаниях)
* В-четвертых, у нас есть проблема: опыт работы может быть представлен только в годах или только месяцах. Например, можно встретить следующие варианты:
    * Опыт работы 3 года 2 месяца…
    * Опыт работы 4 года…
    * Опыт работы 11 месяцев…
    * Учитывайте эту особенность в вашем коде

Учитывайте эту особенность в вашем коде

В результате преобразования у вас должен получиться столбец, содержащий информацию о том, сколько месяцев проработал соискатель.
Выполните преобразование, ответьте на контрольные вопросы и удалите столбец **"Опыт работы"** из таблицы.

In [ ]:
def exp_mnth (text):

    if pd.isna(text) or not isinstance(text, str):
        return np.nan
    
    # Приводим к нижнему регистру для сравнения
    text_lower = text.lower().strip()
       
    # Если текст слишком короткий или не содержит цифр - скорее всего нет данных
    if len(text) < 3 or not re.search(r'\d+', text):
        return np.nan
    
    years = 0
    months = 0
    
    # Поиск лет (год/года/лет)
    years_match = re.search(r'(\d+)\s*(?:год|года|лет)', text)
    if years_match:
        years = int(years_match.group(1))
    
    # Поиск месяцев (месяц/месяца/месяцев)
    months_match = re.search(r'(\d+)\s*(?:месяц|месяца|месяцев)', text)
    if months_match:
        months = int(months_match.group(1))
    
    # Если не нашли ни лет, ни месяцев - возвращаем NaN
    if years == 0 and months == 0:
        return np.nan
    
    total_months = years * 12 + months
    return total_months

hhdata['Опыт мес'] = hhdata['Опыт работы'].apply(exp_mnth)



exp_median = hhdata['Опыт мес'].median()
print(exp_median)

hhdata.head(5)

100.0

,"Пол, возраст",ЗП,Ищет работу на должность:,"Город, переезд, командировки",Занятость,График,Опыт работы,Последнее/нынешнее место работы,Последняя/нынешняя должность,Образование и ВУЗ,Обновление резюме,Авто,Образование,Пол,Возраст и ДР,Возраст,Опыт мес
0,"Мужчина , 39 лет , родился 27 ноября 1979",29000 руб.,Системный администратор,"Советск (Калининградская область) , не готов к...","частичная занятость, проектная работа, полная ...","гибкий график, полный день, сменный график, ва...",Опыт работы 16 лет 10 месяцев Август 2010 — п...,"МАОУ ""СОШ № 1 г.Немана""",Системный администратор,Неоконченное высшее образование 2000 Балтийск...,16.04.2019 15:59,Имеется собственный автомобиль,[Неоконченное высшее],[Мужчина ],"[ 39 лет , родился 27 ноября 1979]",39,202.0
1,"Мужчина , 60 лет , родился 20 марта 1959",40000 руб.,Технический писатель,"Королев , не готов к переезду , готов к редким...","частичная занятость, проектная работа, полная ...","гибкий график, полный день, сменный график, уд...",Опыт работы 19 лет 5 месяцев Январь 2000 — по...,Временный трудовой коллектив,"Менеджер проекта, Аналитик, Технический писатель",Высшее образование 1981 Военно-космическая ак...,12.04.2019 08:42,Не указано,[Высшее],[Мужчина ],"[ 60 лет , родился 20 марта 1959]",60,233.0
2,"Женщина , 36 лет , родилась 12 августа 1982",20000 руб.,Оператор,"Тверь , не готова к переезду , не готова к ком...",полная занятость,полный день,Опыт работы 10 лет 3 месяца Октябрь 2004 — Де...,ПАО Сбербанк,Кассир-операционист,Среднее специальное образование 2002 Профессио...,16.04.2019 08:35,Не указано,[Среднее специальное],[Женщина ],"[ 36 лет , родилась 12 августа 1982]",36,123.0
3,"Мужчина , 38 лет , родился 25 июня 1980",100000 руб.,Веб-разработчик (HTML / CSS / JS / PHP / базы ...,"Саратов , не готов к переезду , готов к редким...","частичная занятость, проектная работа, полная ...","гибкий график, удаленная работа",Опыт работы 18 лет 9 месяцев Август 2017 — Ап...,OpenSoft,Инженер-программист,Высшее образование 2002 Саратовский государст...,08.04.2019 14:23,Не указано,[Высшее],[Мужчина ],"[ 38 лет , родился 25 июня 1980]",38,225.0
4,"Женщина , 26 лет , родилась 3 марта 1993",140000 руб.,Региональный менеджер по продажам,"Москва , не готова к переезду , готова к коман...",полная занятость,полный день,Опыт работы 5 лет 7 месяцев Региональный мене...,Мармелад,Менеджер по продажам,Высшее образование 2015 Кгу Психологии и педаг...,22.04.2019 10:32,Не указано,[Высшее],[Женщина ],"[ 26 лет , родилась 3 марта 1993]",26,67.0

In [ ]:
hhdata = hhdata.drop('Опыт работы', axis=1)
hhdata

,"Пол, возраст",ЗП,Ищет работу на должность:,"Город, переезд, командировки",Занятость,График,Последнее/нынешнее место работы,Последняя/нынешняя должность,Образование и ВУЗ,Обновление резюме,Авто,Образование,Пол,Возраст и ДР,Возраст,Опыт мес
0,"Мужчина , 39 лет , родился 27 ноября 1979",29000 руб.,Системный администратор,"Советск (Калининградская область) , не готов к...","частичная занятость, проектная работа, полная ...","гибкий график, полный день, сменный график, ва...","МАОУ ""СОШ № 1 г.Немана""",Системный администратор,Неоконченное высшее образование 2000 Балтийск...,16.04.2019 15:59,Имеется собственный автомобиль,[Неоконченное высшее],[Мужчина ],"[ 39 лет , родился 27 ноября 1979]",39,202.0
1,"Мужчина , 60 лет , родился 20 марта 1959",40000 руб.,Технический писатель,"Королев , не готов к переезду , готов к редким...","частичная занятость, проектная работа, полная ...","гибкий график, полный день, сменный график, уд...",Временный трудовой коллектив,"Менеджер проекта, Аналитик, Технический писатель",Высшее образование 1981 Военно-космическая ак...,12.04.2019 08:42,Не указано,[Высшее],[Мужчина ],"[ 60 лет , родился 20 марта 1959]",60,233.0
2,"Женщина , 36 лет , родилась 12 августа 1982",20000 руб.,Оператор,"Тверь , не готова к переезду , не готова к ком...",полная занятость,полный день,ПАО Сбербанк,Кассир-операционист,Среднее специальное образование 2002 Профессио...,16.04.2019 08:35,Не указано,[Среднее специальное],[Женщина ],"[ 36 лет , родилась 12 августа 1982]",36,123.0
3,"Мужчина , 38 лет , родился 25 июня 1980",100000 руб.,Веб-разработчик (HTML / CSS / JS / PHP / базы ...,"Саратов , не готов к переезду , готов к редким...","частичная занятость, проектная работа, полная ...","гибкий график, удаленная работа",OpenSoft,Инженер-программист,Высшее образование 2002 Саратовский государст...,08.04.2019 14:23,Не указано,[Высшее],[Мужчина ],"[ 38 лет , родился 25 июня 1980]",38,225.0
4,"Женщина , 26 лет , родилась 3 марта 1993",140000 руб.,Региональный менеджер по продажам,"Москва , не готова к переезду , готова к коман...",полная занятость,полный день,Мармелад,Менеджер по продажам,Высшее образование 2015 Кгу Психологии и педаг...,22.04.2019 10:32,Не указано,[Высшее],[Женщина ],"[ 26 лет , родилась 3 марта 1993]",26,67.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44739,"Мужчина , 30 лет , родился 17 января 1989",50000 руб.,"Финансист, аналитик, экономист, бухгалтер, мен...","Тверь , готов к переезду (Москва, Химки) , гот...",полная занятость,"полный день, удаленная работа","ООО ""IAS"" (независимый участник объединения Ru...",Руководитель субгруппы,Высшее образование 2015 Московский гуманитарн...,22.04.2019 12:32,Не указано,[Высшее],[Мужчина ],"[ 30 лет , родился 17 января 1989]",30,91.0
44740,"Мужчина , 27 лет , родился 5 марта 1992",39000 руб.,"Системный администратор, IT-специалист","Липецк , готов к переезду , готов к командировкам","проектная работа, частичная занятость, полная ...","удаленная работа, гибкий график, полный день, ...",ИП Пестрецов,Предприниматель,Высшее образование (Бакалавр) 2016 Воронежски...,22.04.2019 13:11,Не указано,[Высшее],[Мужчина ],"[ 27 лет , родился 5 марта 1992]",27,91.0
44741,"Женщина , 48 лет , родилась 26 декабря 1970",40000 руб.,"Аналитик данных, Математик","Челябинск , готова к переезду , готова к редки...",полная занятость,"полный день, удаленная работа","ОАО «ЧМК», Исследовательско-Технологический Це...",Начальник группы аналитики,Высшее образование 2000 Южно-Уральский госуда...,09.04.2019 05:07,Не указано,[Высшее],[Женщина ],"[ 48 лет , родилась 26 декабря 1970]",48,257.0
44742,"Мужчина , 24 года , родился 6 октября 1994",20000 руб.,Контент-менеджер,"Тамбов , не готов к переезду , не готов к кома...","частичная занятость, полная занятость",удаленная работа,IQ-Maxima,Менеджер проектов,Высшее образование 2015 Тамбовский государств...,26.04.2019 14:25,Имеется собственный автомобиль,[Высшее],[Мужчина ],"[ 24 года , родился 6 октября 1994]",24,46.0
44743,"Мужчина , 38 лет , родился 25 апреля 1980",120000 руб.,Руководитель проекта,"Москва , не готов к переезду , не готов к кома...",полная занятость,полный день,ПАО ГК ТНС энерго,Руководитель отдела технической поддержки,Высшее образование 1997 Южно-Российский госуд...,05.07.2018 20:15,Не указано,[Высшее],[Мужчина ],"[ 38 лет , родился 25 апреля 1980]",38,190.0

4. Хорошо идем! Следующий на очереди признак "Город, переезд, командировки". Информация в нем представлена в следующем виде: **<Город , (метро) , готовность к переезду (города для переезда) , готовность к командировкам>**. В скобках указаны необязательные параметры строки. Например, можно встретить следующие варианты:

* Москва , не готов к переезду , готов к командировкам
* Москва , м. Беломорская , не готов к переезду, не готов к командировкам
* Воронеж , готов к переезду (Сочи, Москва, Санкт-Петербург) , готов к командировкам

Создадим отдельные признаки **"Город"**, **"Готовность к переезду"**, **"Готовность к командировкам"**. При этом важно учесть:

* Признак **"Город"** должен содержать только 4 категории: "Москва", "Санкт-Петербург" и "город-миллионник" (их список ниже), остальные обозначьте как "другие".

    Список городов-миллионников:
    
   <code>million_cities = ['Новосибирск', 'Екатеринбург','Нижний Новгород','Казань', 'Челябинск','Омск', 'Самара', 'Ростов-на-Дону', 'Уфа', 'Красноярск', 'Пермь', 'Воронеж','Волгоград']
    </code>
    Инфорация о метро, рядом с которым проживает соискатель нас не интересует.
* Признак **"Готовность к переезду"** должен иметь два возможных варианта: True или False. Обратите внимание, что возможны несколько вариантов описания готовности к переезду в признаке "Город, переезд, командировки". Например:
    * … , готов к переезду , …
    * … , не готова к переезду , …
    * … , готова к переезду (Москва, Санкт-Петербург, Ростов-на-Дону)
    * … , хочу переехать (США) , …
    
    Нас интересует только сам факт возможности или желания переезда.
* Признак **"Готовность к командировкам"** должен иметь два возможных варианта: True или False. Обратите внимание, что возможны несколько вариантов описания готовности к командировкам в признаке "Город, переезд, командировки". Например:
    * … , готов к командировкам , … 
    * … , готова к редким командировкам , …
    * … , не готов к командировкам , …
    
    Нас интересует только сам факт готовности к командировке.
    
    Еще один важный факт: при выгрузки данных у некоторых соискателей "потерялась" информация о готовности к командировкам. Давайте по умолчанию будем считать, что такие соискатели не готовы к командировкам.
    
Выполните преобразования и удалите столбец **"Город, переезд, командировки"** из таблицы.

*Совет: обратите внимание на то, что структура текста может меняться в зависимости от указания ближайшего метро. Учите это, если будете использовать порядок слов в своей программе.*

In [ ]:
MILLION_CITIES = {
    'Новосибирск', 'Екатеринбург', 'Нижний Новгород', 'Казань',
    'Челябинск', 'Омск', 'Самара', 'Ростов-на-Дону', 'Уфа',
    'Красноярск', 'Пермь', 'Воронеж', 'Волгоград'
}

# =====================================================
# 2. ФУНКЦИЯ ПАРСИНГА БЕЗ ИСКЛЮЧЕНИЙ
# =====================================================

def extract_city_no_exceptions(text):
    """
    Извлекает город из строки БЕЗ учета слов-исключений.
    Используется для анализа ошибок.
    """
    if pd.isna(text) or not isinstance(text, str):
        return np.nan
    
    text = str(text).strip()
    
    # Приоритет 1: Москва
    if 'Москва' in text:
        return 'Москва'
    
    # Приоритет 2: Санкт-Петербург
    if 'Санкт-Петербург' in text or 'СПб' in text:
        return 'Санкт-Петербург'
    
    # Приоритет 3: Города-миллионники
    for city in MILLION_CITIES:
        if city in text:
            return city
    
    # Приоритет 4: Первое слово с заглавной буквы (БЕЗ ИСКЛЮЧЕНИЙ!)
    first_word_match = re.search(r'^([А-Я][а-я]+(?:-[А-Я][а-я]+)?)', text)
    if first_word_match:
        return first_word_match.group(1)
    
    return 'другие'

def analyze_city_errors(df, location_column='Город, переезд, командировки'):
    """
    Анализирует результаты парсинга городов без исключений
    и выявляет потенциальные ошибки.
    """
    # Создаем копию данных
    df_analysis = hhdata.copy()
    
    # Парсим города БЕЗ исключений
    df_analysis['city_raw'] = df_analysis['Город, переезд, командировки'].apply(extract_city_no_exceptions)
    
    # 1. ТОП-20 самых частых "городов"
    print("\n" + "=" * 80)
    print("📊 ТОП-20 САМЫХ ЧАСТЫХ 'ГОРОДОВ' (БЕЗ ИСКЛЮЧЕНИЙ)")
    print("=" * 80)
    
    city_counts = df_analysis['city_raw'].value_counts().head(20)
    print(city_counts.to_string())
    
    # 2. Выявляем подозрительные слова (потенциальные ошибки)
    # Список слов, которые точно не являются городами
    known_non_cities = {
        'Готов', 'Не', 'Нет', 'Без', 'С', 'По', 
        'На', 'В', 'Из', 'От', 'До', 'При',
        'Опыт', 'Работа', 'Стаж', 'Год', 'Месяц',
        'Более', 'Менее', 'Около', 'Примерно',
        'Высшее', 'Среднее', 'Начальное'
    }
    
    # Находим потенциальные ошибки
    potential_errors = []
    for city, count in city_counts.items():
        if city in known_non_cities:
            potential_errors.append((city, count, 'явно не город'))
        elif len(city) <= 2:
            potential_errors.append((city, count, 'слишком короткое слово'))
        elif city.isdigit():
            potential_errors.append((city, count, 'цифры'))
        elif city in ['И', 'А', 'Но', 'За']:
            potential_errors.append((city, count, 'предлог/союз'))
    
    # 3. Выводим подозрительные города
    print("\n" + "=" * 80)
    print("⚠️ ПОДОЗРИТЕЛЬНЫЕ 'ГОРОДА' (ВЕРОЯТНЫЕ ОШИБКИ)")
    print("=" * 80)
    
    if potential_errors:
        df_errors = pd.DataFrame(potential_errors, columns=['Слово', 'Частота', 'Причина'])
        print(df_errors.to_string(index=False))
    else:
        print("✅ Подозрительных слов не найдено")
    
    # 4. Показываем примеры строк с подозрительными словами
    print("\n" + "=" * 80)
    print("📝 ПРИМЕРЫ СТРОК С ПОДОЗРИТЕЛЬНЫМИ СЛОВАМИ")
    print("=" * 80)
    
    suspicious_words = [item[0] for item in potential_errors if item[0] in known_non_cities]
    
    for word in suspicious_words[:5]:  # показываем первые 5
        examples = df_analysis[df_analysis['city_raw'] == word][location_column].head(3)
        print(f"\nСлово: '{word}' (встречается {len(df_analysis[df_analysis['city_raw'] == word])} раз)")
        for example in examples:
            print(f"  → {example[:80]}...")
    
    # 5. Рекомендации по добавлению в список исключений
    print("\n" + "=" * 80)
    print("💡 РЕКОМЕНДАЦИИ ПО ДОБАВЛЕНИЮ В СПИСОК ИСКЛЮЧЕНИЙ")
    print("=" * 80)
    
    new_exceptions = []
    for word, count, reason in potential_errors:
        if word in known_non_cities:
            new_exceptions.append(word)
    
    if new_exceptions:
        print("Рекомендуется добавить следующие слова в список исключений:")
        print(f"EXCLUDED_WORDS = {set(new_exceptions)}")
        
        # Проверяем, какие уже есть в текущем списке
        current_exceptions = {'Готов', 'Не', 'Нет', 'Без', 'С', 'По'}
        new_words = set(new_exceptions) - current_exceptions
        if new_words:
            print(f"\nНовые слова для добавления: {new_words}")
        else:
            print("\nВсе подозрительные слова уже есть в списке исключений ✅")
    else:
        print("Новых слов для исключения не найдено")
    
    return df_analysis

# =====================================================
# 4. ДЕТАЛЬНЫЙ АНАЛИЗ ОШИБОК
# =====================================================

def detailed_error_analysis(df, location_column='location'):
    """
    Более детальный анализ ошибок с группировкой по типам.
    """
    df_analysis = df.copy()
    df_analysis['city_raw'] = df_analysis[location_column].apply(extract_city_no_exceptions)
    
        # Категоризация результатов
    def categorize_city(city):
        if pd.isna(city):
            return 'пустое'
        if city in ['Москва', 'Санкт-Петербург']:
            return 'ключевой'
        if city in MILLION_CITIES:
            return 'миллионник'
        if city in ['Готов', 'Не', 'Нет', 'Без', 'С', 'По', 'На', 'В', 'Из']:
            return 'служебное_слово'
        if len(city) <= 2:
            return 'короткое_слово'
        if city.isdigit():
            return 'цифры'
        return 'другой_город'
    
    df_analysis['category'] = df_analysis['city_raw'].apply(categorize_city)
    
    print("\n" + "=" * 80)
    print("📊 КАТЕГОРИЗАЦИЯ РЕЗУЛЬТАТОВ ПАРСИНГА")
    print("=" * 80)
    
    category_stats = df_analysis['category'].value_counts()
    print(category_stats.to_string())
    
    # Детали по каждой категории
    categories = {
        'служебное_слово': 'Служебные слова (ошибки!)',
        'короткое_слово': 'Слова короче 3 букв (вероятные ошибки)',
        'цифры': 'Цифры (точно ошибки)',
        'другой_город': 'Другие города (вероятно корректные)',
        'ключевой': 'Москва/СПб (корректно)',
        'миллионник': 'Города-миллионники (корректно)',
        'пустое': 'Пустые значения'
    }
    
    print("\n" + "=" * 80)
    print("🔍 ДЕТАЛИ ПО КАТЕГОРИЯМ")
    print("=" * 80)
    
    for category, description in categories.items():
        if category in category_stats.index:
            count = category_stats[category]
            examples = df_analysis[df_analysis['category'] == category]['city_raw'].head(5).tolist()
            print(f"\n{description}: {count} записей")
            print(f"  Примеры: {', '.join(map(str, examples))}")
    
    return df_analysis
    
hhdata_analyzed = analyze_city_errors(hhdata)
#df_detailed = detailed_error_analysis(hhdata)

================================================================================
📊 ТОП-20 САМЫХ ЧАСТЫХ 'ГОРОДОВ' (БЕЗ ИСКЛЮЧЕНИЙ)
================================================================================
city_raw
Москва             18707
Санкт-Петербург     5064
Краснодар            992
Новосибирск          933
Казань               830
Екатеринбург         686
Самара               662
Ростов-на-Дону       598
Нижний Новгород      565
Воронеж              526
Уфа                  516
Алматы               488
Пермь                412
Красноярск           391
Минск                348
Тюмень               327
Челябинск            305
Волгоград            272
Омск                 265
Томск                254

================================================================================
⚠️ ПОДОЗРИТЕЛЬНЫЕ 'ГОРОДА' (ВЕРОЯТНЫЕ ОШИБКИ)
================================================================================
✅ Подозрительных слов не найдено

================================================================================
📝 ПРИМЕРЫ СТРОК С ПОДОЗРИТЕЛЬНЫМИ СЛОВАМИ
================================================================================

================================================================================
💡 РЕКОМЕНДАЦИИ ПО ДОБАВЛЕНИЮ В СПИСОК ИСКЛЮЧЕНИЙ
================================================================================
Новых слов для исключения не найдено

In [ ]:
million_cities = [
    'Новосибирск', 'Екатеринбург', 'Нижний Новгород', 'Казань',
    'Челябинск', 'Омск', 'Самара', 'Ростов-на-Дону', 'Уфа',
    'Красноярск', 'Пермь', 'Воронеж', 'Волгоград'
]

# =====================================================
# 2. LAMBDA ФУНКЦИИ (ОЧЕНЬ ПРОСТЫЕ)
# =====================================================

# Функция для определения города
get_city = lambda x: (
    'не указан' if pd.isna(x) or not isinstance(x, str) else
    'Москва' if 'Москва' in x else
    'Санкт-Петербург' if 'Санкт-Петербург' in x or 'СПб' in x else
    'миллионник' if any(city in x for city in million_cities) else
    'другой'
)

# Функция для определения готовности к переезду
get_relocate = lambda x: (
    False if pd.isna(x) or not isinstance(x, str) or 'не готов' in x.lower() else True
)

# Функция для определения готовности к командировкам
get_travel = lambda x: (
    False if pd.isna(x) or not isinstance(x, str) or 'не готов' in x.lower() else True
)

hhdata['Город'] = hhdata['Город, переезд, командировки'].apply(get_city)

# Создаем столбец с готовностью к переезду
hhdata['Переезд'] = hhdata['Город, переезд, командировки'].apply(get_relocate)

# Создаем столбец с готовностью к командировкам
hhdata['Командировки'] = hhdata['Город, переезд, командировки'].apply(get_travel)

hhdata.head(5)

,"Пол, возраст",ЗП,Ищет работу на должность:,"Город, переезд, командировки",Занятость,График,Последнее/нынешнее место работы,Последняя/нынешняя должность,Образование и ВУЗ,Обновление резюме,Авто,Образование,Пол,Возраст и ДР,Возраст,Опыт мес,Город,Переезд,Командировки
0,"Мужчина , 39 лет , родился 27 ноября 1979",29000 руб.,Системный администратор,"Советск (Калининградская область) , не готов к...","частичная занятость, проектная работа, полная ...","гибкий график, полный день, сменный график, ва...","МАОУ ""СОШ № 1 г.Немана""",Системный администратор,Неоконченное высшее образование 2000 Балтийск...,16.04.2019 15:59,Имеется собственный автомобиль,[Неоконченное высшее],[Мужчина ],"[ 39 лет , родился 27 ноября 1979]",39,202.0,другой,False,False
1,"Мужчина , 60 лет , родился 20 марта 1959",40000 руб.,Технический писатель,"Королев , не готов к переезду , готов к редким...","частичная занятость, проектная работа, полная ...","гибкий график, полный день, сменный график, уд...",Временный трудовой коллектив,"Менеджер проекта, Аналитик, Технический писатель",Высшее образование 1981 Военно-космическая ак...,12.04.2019 08:42,Не указано,[Высшее],[Мужчина ],"[ 60 лет , родился 20 марта 1959]",60,233.0,другой,False,False
2,"Женщина , 36 лет , родилась 12 августа 1982",20000 руб.,Оператор,"Тверь , не готова к переезду , не готова к ком...",полная занятость,полный день,ПАО Сбербанк,Кассир-операционист,Среднее специальное образование 2002 Профессио...,16.04.2019 08:35,Не указано,[Среднее специальное],[Женщина ],"[ 36 лет , родилась 12 августа 1982]",36,123.0,другой,False,False
3,"Мужчина , 38 лет , родился 25 июня 1980",100000 руб.,Веб-разработчик (HTML / CSS / JS / PHP / базы ...,"Саратов , не готов к переезду , готов к редким...","частичная занятость, проектная работа, полная ...","гибкий график, удаленная работа",OpenSoft,Инженер-программист,Высшее образование 2002 Саратовский государст...,08.04.2019 14:23,Не указано,[Высшее],[Мужчина ],"[ 38 лет , родился 25 июня 1980]",38,225.0,другой,False,False
4,"Женщина , 26 лет , родилась 3 марта 1993",140000 руб.,Региональный менеджер по продажам,"Москва , не готова к переезду , готова к коман...",полная занятость,полный день,Мармелад,Менеджер по продажам,Высшее образование 2015 Кгу Психологии и педаг...,22.04.2019 10:32,Не указано,[Высшее],[Женщина ],"[ 26 лет , родилась 3 марта 1993]",26,67.0,Москва,False,False

In [ ]:
spb_share = len(hhdata[hhdata['Город'] == 'Санкт-Петербург'])/len(hhdata)*100
spb_share

ready = (hhdata['Переезд'] == True) & (hhdata['Командировки'] == True)
ready_count = ready.sum()

ready_share = (ready_count/len(hhdata))*100
ready_share

np.float64(32.03558018952262)

5. Рассмотрим поближе признаки **"Занятость"** и **"График"**. Сейчас признаки представляют собой набор категорий желаемой занятости (полная занятость, частичная занятость, проектная работа, волонтерство, стажировка) и желаемого графика работы (полный день, сменный график, гибкий график, удаленная работа, вахтовый метод).
На сайте hh.ru соискатель может указывать различные комбинации данных категорий, например:
* полная занятость, частичная занятость
* частичная занятость, проектная работа, волонтерство
* полный день, удаленная работа
* вахтовый метод, гибкий график, удаленная работа, полная занятость

Такой вариант признаков имеет множество различных комбинаций, а значит множество уникальных значений, что мешает анализу. Нужно это исправить!

Давайте создадим признаки-мигалки для каждой категории: если категория присутствует в списке желаемых соискателем, то в столбце на месте строки рассматриваемого соискателя ставится True, иначе - False.

Такой метод преобразования категориальных признаков называется One Hot Encoding и его схема представлена на рисунке ниже:
<img src=https://raw.githubusercontent.com/AndreyRysistov/DatasetsForPandas/main/ohe.jpg>
Выполните данное преобразование для признаков "Занятость" и "График", ответьте на контрольные вопросы, после чего удалите их из таблицы

In [ ]:
full = lambda x: (
    False if pd.isna(x) or not isinstance(x, str) else True if 'полная' in x else False
)

part = lambda x: (
    False if pd.isna(x) or not isinstance(x, str) else True if 'частичная' in x else False
)

project = lambda x: (
    False if pd.isna(x) or not isinstance(x, str) else True if 'проектная' in x else False
)

intern = lambda x: (
    False if pd.isna(x) or not isinstance(x, str) else True if 'стажировка' in x else False
)

vol = lambda x: (
    False if pd.isna(x) or not isinstance(x, str) else True if 'волонт' in x else False
)

vacht = lambda x: (
    False if pd.isna(x) or not isinstance(x, str) else True if 'вахт' in x else False
)
flex  = lambda x: (
    False if pd.isna(x) or not isinstance(x, str) else True if 'гибк' in x else False
)

hhdata['Полная занятость'] = hhdata['Занятость'].apply(full)
hhdata['Частичная занятость'] = hhdata['Занятость'].apply(part)
hhdata['Проетная работа'] = hhdata['Занятость'].apply(project)
hhdata['Стажировка'] = hhdata['Занятость'].apply(intern)
hhdata['Волонтерство'] = hhdata['Занятость'].apply(vol)
hhdata['Вахта'] = hhdata['График'].apply(vacht)
hhdata['Гибкий график'] = hhdata['График'].apply(flex)

hhdata.head(5)

,"Пол, возраст",ЗП,Ищет работу на должность:,"Город, переезд, командировки",Занятость,График,Последнее/нынешнее место работы,Последняя/нынешняя должность,Образование и ВУЗ,Обновление резюме,...,Город,Переезд,Командировки,Полная занятость,Частичная занятость,Проетная работа,Стажировка,Волонтерство,Вахта,Гибкий график
0,"Мужчина , 39 лет , родился 27 ноября 1979",29000 руб.,Системный администратор,"Советск (Калининградская область) , не готов к...","частичная занятость, проектная работа, полная ...","гибкий график, полный день, сменный график, ва...","МАОУ ""СОШ № 1 г.Немана""",Системный администратор,Неоконченное высшее образование 2000 Балтийск...,16.04.2019 15:59,...,другой,False,False,True,True,True,False,False,True,True
1,"Мужчина , 60 лет , родился 20 марта 1959",40000 руб.,Технический писатель,"Королев , не готов к переезду , готов к редким...","частичная занятость, проектная работа, полная ...","гибкий график, полный день, сменный график, уд...",Временный трудовой коллектив,"Менеджер проекта, Аналитик, Технический писатель",Высшее образование 1981 Военно-космическая ак...,12.04.2019 08:42,...,другой,False,False,True,True,True,False,False,False,True
2,"Женщина , 36 лет , родилась 12 августа 1982",20000 руб.,Оператор,"Тверь , не готова к переезду , не готова к ком...",полная занятость,полный день,ПАО Сбербанк,Кассир-операционист,Среднее специальное образование 2002 Профессио...,16.04.2019 08:35,...,другой,False,False,True,False,False,False,False,False,False
3,"Мужчина , 38 лет , родился 25 июня 1980",100000 руб.,Веб-разработчик (HTML / CSS / JS / PHP / базы ...,"Саратов , не готов к переезду , готов к редким...","частичная занятость, проектная работа, полная ...","гибкий график, удаленная работа",OpenSoft,Инженер-программист,Высшее образование 2002 Саратовский государст...,08.04.2019 14:23,...,другой,False,False,True,True,True,False,False,False,True
4,"Женщина , 26 лет , родилась 3 марта 1993",140000 руб.,Региональный менеджер по продажам,"Москва , не готова к переезду , готова к коман...",полная занятость,полный день,Мармелад,Менеджер по продажам,Высшее образование 2015 Кгу Психологии и педаг...,22.04.2019 10:32,...,Москва,False,False,True,False,False,False,False,False,False

In [ ]:
proj_vol = (hhdata['Проетная работа'] == True) & (hhdata['Волонтерство'] == True)
count_proj_vol = proj_vol.sum()
print(count_proj_vol)

vacht_fl = (hhdata['Вахта'] == True) & (hhdata['Гибкий график'] == True)
count_vacht_fl = vacht_fl.sum()
print(count_vacht_fl)

436
2311

In [ ]:
hhdata.head(5)

,"Пол, возраст",ЗП,Ищет работу на должность:,"Город, переезд, командировки",Занятость,График,Последнее/нынешнее место работы,Последняя/нынешняя должность,Образование и ВУЗ,Обновление резюме,...,Опыт мес,Город,Переезд,Командировки,Частичная занятость,Проетная работа,Стажировка,Волонтерство,Вахта,Гибкий график
0,"Мужчина , 39 лет , родился 27 ноября 1979",29000 руб.,Системный администратор,"Советск (Калининградская область) , не готов к...","частичная занятость, проектная работа, полная ...","гибкий график, полный день, сменный график, ва...","МАОУ ""СОШ № 1 г.Немана""",Системный администратор,Неоконченное высшее образование 2000 Балтийск...,16.04.2019 15:59,...,202.0,другой,False,False,True,True,False,False,True,True
1,"Мужчина , 60 лет , родился 20 марта 1959",40000 руб.,Технический писатель,"Королев , не готов к переезду , готов к редким...","частичная занятость, проектная работа, полная ...","гибкий график, полный день, сменный график, уд...",Временный трудовой коллектив,"Менеджер проекта, Аналитик, Технический писатель",Высшее образование 1981 Военно-космическая ак...,12.04.2019 08:42,...,233.0,другой,False,False,True,True,False,False,False,True
2,"Женщина , 36 лет , родилась 12 августа 1982",20000 руб.,Оператор,"Тверь , не готова к переезду , не готова к ком...",полная занятость,полный день,ПАО Сбербанк,Кассир-операционист,Среднее специальное образование 2002 Профессио...,16.04.2019 08:35,...,123.0,другой,False,False,False,False,False,False,False,False
3,"Мужчина , 38 лет , родился 25 июня 1980",100000 руб.,Веб-разработчик (HTML / CSS / JS / PHP / базы ...,"Саратов , не готов к переезду , готов к редким...","частичная занятость, проектная работа, полная ...","гибкий график, удаленная работа",OpenSoft,Инженер-программист,Высшее образование 2002 Саратовский государст...,08.04.2019 14:23,...,225.0,другой,False,False,True,True,False,False,False,True
4,"Женщина , 26 лет , родилась 3 марта 1993",140000 руб.,Региональный менеджер по продажам,"Москва , не готова к переезду , готова к коман...",полная занятость,полный день,Мармелад,Менеджер по продажам,Высшее образование 2015 Кгу Психологии и педаг...,22.04.2019 10:32,...,67.0,Москва,False,False,False,False,False,False,False,False

6. (2 балла) Наконец, мы добрались до самого главного и самого важного - признака заработной платы **"ЗП"**. 
В чем наша беда? В том, что помимо желаемой заработной платы соискатель указывает валюту, в которой он бы хотел ее получать, например:
* 30000 руб.
* 50000 грн.
* 550 USD

Нам бы хотелось видеть заработную плату в единой валюте, например, в рублях. Возникает вопрос, а где взять курс валют по отношению к рублю?

На самом деле язык Python имеет в арсенале огромное количество возможностей получения данной информации, от обращения к API Центробанка, до использования специальных библиотек, например pycbrf. Однако, это не тема нашего проекта.

Поэтому мы пойдем в лоб: обратимся к специальным интернет-ресурсам для получения данных о курсе в виде текстовых файлов. Например, MDF.RU, данный ресурс позволяет удобно экспортировать данные о курсах различных валют и акций за указанные периоды в виде csv файлов. Мы уже сделали выгрузку курсов валют, которые встречаются в наших данных за период с 29.12.2017 по 05.12.2019. Скачать ее вы можете **на платформе**

Создайте новый DataFrame из полученного файла. В полученной таблице нас будут интересовать столбцы:
* "currency" - наименование валюты в ISO кодировке,
* "date" - дата, 
* "proportion" - пропорция, 
* "close" - цена закрытия (последний зафиксированный курс валюты на указанный день).


Перед вами таблица соответствия наименований иностранных валют в наших данных и их общепринятых сокращений, которые представлены в нашем файле с курсами валют. Пропорция - это число, за сколько единиц валюты указан курс в таблице с курсами. Например, для казахстанского тенге курс на 20.08.2019 составляет 17.197 руб. за 100 тенге, тогда итоговый курс равен - 17.197 / 100 = 0.17197 руб за 1 тенге.
Воспользуйтесь этой информацией в ваших преобразованиях.

<img src=https://raw.githubusercontent.com/AndreyRysistov/DatasetsForPandas/main/table.jpg>


Осталось только понять, откуда брать дату, по которой определяется курс? А вот же она - в признаке **"Обновление резюме"**, в нем содержится дата и время, когда соискатель выложил текущий вариант своего резюме. Нас интересует только дата, по ней бы и будем сопоставлять курсы валют.

Теперь у нас есть вся необходимая информация для того, чтобы создать признак "ЗП (руб)" - заработная плата в рублях.

После ответа на контрольные вопросы удалите исходный столбец заработной платы "ЗП" и все промежуточные столбцы, если вы их создавали.

Итак, давайте обсудим возможный алгоритм преобразования: 
1. Перевести признак "Обновление резюме" из таблицы с резюме в формат datetime и достать из него дату. В тот же формат привести признак "date" из таблицы с валютами.
2. Выделить из столбца "ЗП" сумму желаемой заработной платы и наименование валюты, в которой она исчисляется. Наименование валюты перевести в стандарт ISO согласно с таблицей выше.
3. Присоединить к таблице с резюме таблицу с курсами по столбцам с датой и названием валюты (подумайте, какой тип объединения надо выбрать, чтобы в таблице с резюме сохранились данные о заработной плате, изначально представленной в рублях). Значение close для рубля заполнить единицей 1 (курс рубля самого к себе)
4. Умножить сумму желаемой заработной платы на присоединенный курс валюты (close) и разделить на пропорцию (обратите внимание на пропуски после объединения в этих столбцах), результат занести в новый столбец "ЗП (руб)".

In [ ]:
#ваш код здесь

# Исследование зависимостей в данных

1. Постройте распределение признака **"Возраст"**. Опишите распределение, отвечая на следующие вопросы: чему равна мода распределения, каковы предельные значения признака, в каком примерном интервале находится возраст большинства соискателей? Есть ли аномалии для признака возраста, какие значения вы бы причислили к их числу?
*Совет: постройте гистограмму и коробчатую диаграмму рядом.*

In [ ]:
# ваш код здесь

ваши выводы по графику здесь

2. Постройте распределение признака **"Опыт работы (месяц)"**. Опишите данное распределение, отвечая на следующие вопросы: чему равна мода распределения, каковы предельные значения признака, в каком примерном интервале находится опыт работы большинства соискателей? Есть ли аномалии для признака опыта работы, какие значения вы бы причислили к их числу?
*Совет: постройте гистограмму и коробчатую диаграмму рядом.*

In [ ]:
# ваш код здесь

ваши выводы здесь

3. Постройте распределение признака **"ЗП (руб)"**. Опишите данное распределение, отвечая на следующие вопросы: каковы предельные значения признака, в каком примерном интервале находится заработная плата большинства соискателей? Есть ли аномалии для признака возраста? Обратите внимание на гигантские размеры желаемой заработной платы.
*Совет: постройте гистограмму и коробчатую диаграмму рядом.*

In [ ]:
# ваш код здесь

ваши выводы здесь

4. Постройте диаграмму, которая показывает зависимость **медианной** желаемой заработной платы (**"ЗП (руб)"**) от уровня образования (**"Образование"**). Используйте для диаграммы данные о резюме, где желаемая заработная плата меньше 1 млн рублей.
*Сделайте выводы по представленной диаграмме: для каких уровней образования наблюдаются наибольшие и наименьшие уровни желаемой заработной платы? Как вы считаете, важен ли признак уровня образования при прогнозировании заработной платы?*

In [ ]:
# ваш код здесь

ваши выводы здесь

5. Постройте диаграмму, которая показывает распределение желаемой заработной платы (**"ЗП (руб)"**) в зависимости от города (**"Город"**). Используйте для диаграммы данные о резюме, где желая заработная плата меньше 1 млн рублей.
*Сделайте выводы по полученной диаграмме: как соотносятся медианные уровни желаемой заработной платы и их размах в городах? Как вы считаете, важен ли признак города при прогнозировании заработной платы?*

In [ ]:
# ваш код здесь

ваши выводы здесь

6. Постройте **многоуровневую столбчатую диаграмму**, которая показывает зависимость медианной заработной платы (**"ЗП (руб)"**) от признаков **"Готовность к переезду"** и **"Готовность к командировкам"**. Проанализируйте график, сравнив уровень заработной платы в категориях.

In [ ]:
# ваш код здесь

In [ ]:
ваши выводы здесь

SyntaxError: invalid syntax (1506124366.py, line 1)

7. Постройте сводную таблицу, иллюстрирующую зависимость **медианной** желаемой заработной платы от возраста (**"Возраст"**) и образования (**"Образование"**). На полученной сводной таблице постройте **тепловую карту**. Проанализируйте тепловую карту, сравнив показатели внутри групп.

In [ ]:
# ваш код здесь

ваши выводы здесь

8. Постройте **диаграмму рассеяния**, показывающую зависимость опыта работы (**"Опыт работы (месяц)"**) от возраста (**"Возраст"**). Опыт работы переведите из месяцев в года, чтобы признаки были в едином масштабе. Постройте на графике дополнительно прямую, проходящую через точки (0, 0) и (100, 100). Данная прямая соответствует значениям, когда опыт работы равен возрасту человека. Точки, лежащие на этой прямой и выше нее - аномалии в наших данных (опыт работы больше либо равен возрасту соискателя)

In [ ]:
# ваш код здесь

ваши выводы здесь

**Дополнительные баллы**

Для получения 2 дополнительных баллов по разведывательному анализу постройте еще два любых содержательных графика или диаграммы, которые помогут проиллюстрировать влияние признаков/взаимосвязь между признаками/распределения признаков. Приведите выводы по ним. Желательно, чтобы в анализе участвовали признаки, которые мы создавали ранее в разделе "Преобразование данных".

In [ ]:
# ваш код здесь

ваши выводы здесь

# Очистка данных

1. Начнем с дубликатов в наших данных. Найдите **полные дубликаты** в таблице с резюме и удалите их.

In [ ]:
# ваш код здесь

2. Займемся пропусками. Выведите информацию **о числе пропусков** в столбцах.

In [ ]:
# ваш код здесь

3. Итак, у нас есть пропуски в 3ех столбцах: **"Опыт работы (месяц)"**, **"Последнее/нынешнее место работы"**, **"Последняя/нынешняя должность"**. Поступим следующим образом: удалите строки, где есть пропуск в столбцах с местом работы и должностью. Пропуски в столбце с опытом работы заполните **медианным** значением.

In [ ]:
# ваш код здесь

4. Мы добрались до ликвидации выбросов. Сначала очистим данные вручную. Удалите резюме, в которых указана заработная плата либо выше 1 млн. рублей, либо ниже 1 тыс. рублей.

In [ ]:
# ваш код здесь

5. В процессе разведывательного анализа мы обнаружили резюме, в которых **опыт работы в годах превышал возраст соискателя**. Найдите такие резюме и удалите их из данных

In [ ]:
# ваш код здесь

6. В результате анализа мы обнаружили потенциальные выбросы в признаке **"Возраст"**. Это оказались резюме людей чересчур преклонного возраста для поиска работы. Попробуйте построить распределение признака в **логарифмическом масштабе**. Добавьте к графику линии, отображающие **среднее и границы интервала метода трех сигм**. Напомним, сделать это можно с помощью метода axvline. Например, для построение линии среднего будет иметь вид:

`histplot.axvline(log_age.mean(), color='k', lw=2)`

В какую сторону асимметрично логарифмическое распределение? Напишите об этом в комментарии к графику.
Найдите выбросы с помощью метода z-отклонения и удалите их из данных, используйте логарифмический масштаб. Давайте сделаем послабление на **1 сигму** (возьмите 4 сигмы) в **правую сторону**.

Выведите таблицу с полученными выбросами и оцените, с каким возрастом соискатели попадают под категорию выбросов?

In [ ]:
# ваш код здесь

ваш коммментарий здесь